version: "3"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - jambo-net 
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management plugin port
    networks:
      - jambo-net

    # network_mode: host
  user-service: 
    build: 
      context: ./backend/services/user/
      dockerfile: Dockerfile
    env_file:
      - ./backend/services/user/configuration/.env
    privileged: true 
    ports:
      - "8001:8001"
    networks:
      - jambo-net

  auth-service: 
    build: 
      context: ./backend/services/auth/
      dockerfile: Dockerfile
    env_file:
      - ./backend/services/auth/configuration/.env
    depends_on:
      - redis
      - user-service
    privileged: true 
    ports: 
      - "8084:8084"
    networks:
      - jambo-net

networks:
   jambo-net:
     driver: bridge
     external: true

  # email-sender:
  #   build:
  #     context: ./External/EmailSender
  #     dockerfile: Dockerfile # Make sure to adjust this if your Dockerfile has a different name
  #   depends_on:
  #     - rabbitmq
  #   network_mode: host
  #   env_file:
  #     - ./External/EmailSender/.env
  #   privileged: true # Added to grant extended privileges to the container

  # jambo-client:
  #   build:
  #     context: ./Jambo/client/
  #     dockerfile: Dockerfile # Make sure to adjust this if your Dockerfile has a different name
  #   depends_on:
  #     - jambo-server
  #   network_mode: host
  #   privileged: true # Added to grant extended privileges to the container
