version: "3"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6378:6378"
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management plugin port

  email-sender:
    build:
      context: ./External/EmailSender
      dockerfile: Dockerfile # Make sure to adjust this if your Dockerfile has a different name
    depends_on:
      - rabbitmq
    network_mode: host
    privileged: true # Added to grant extended privileges to the container

  # jambo-server:
  #   build:
  #     context: ./JamboApp/jambo
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - rabbitmq
  #   ports:
  #     - "8080:8080" # Adjust the port as needed
