version: "3"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6378:6378"
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management plugin port

  email-sender:
    build:
      context: ./External/EmailSender
      dockerfile: Dockerfile # Make sure to adjust this if your Dockerfile has a different name
    depends_on:
      - rabbitmq
    network_mode: host
    env_file:
      - ./External/EmailSender/.env
    privileged: true # Added to grant extended privileges to the container

  jambo-server:
    build:
      context: ./Jambo/server
      dockerfile: Dockerfile # Make sure to adjust this if your Dockerfile has a different name
    depends_on:
      - rabbitmq
      - redis
    network_mode: host
    env_file:
      - ./Jambo/server/app/.env
    privileged: true # Added to grant extended privileges to the container
